# Generated by Django 5.1.3 on 2024-11-20 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=200, unique=True)),
                (
                    "username",
                    models.CharField(default="None", max_length=200, unique=True),
                ),
                ("cnic", models.CharField(default="None", max_length=200, unique=True)),
                ("phone", models.CharField(default="None", max_length=200)),
                ("join_as", models.CharField(default="None", max_length=200)),
                (
                    "description",
                    models.CharField(default="No description", max_length=2000),
                ),
                ("profile", models.CharField(default="None", max_length=200)),
                ("org_name", models.CharField(default="None", max_length=200)),
                ("org_website", models.CharField(default="None", max_length=200)),
                ("org_email", models.CharField(default="None", max_length=200)),
                ("location", models.CharField(default="None", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Jobs",
            fields=[
                ("company_username", models.CharField(max_length=200)),
                ("id", models.AutoField(default=1, primary_key=True, serialize=False)),
                (
                    "job_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("job_title", models.CharField(max_length=400)),
                ("job_description", models.TextField()),
                ("job_type", models.CharField(max_length=200)),
                ("job_EndDate", models.TextField()),
                ("job_budget", models.FloatField()),
                ("job_duration", models.IntegerField()),
                ("required_skills", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=200)),
                ("receiver", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Signup_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joinas", models.CharField(max_length=200)),
                ("fname", models.CharField(max_length=200)),
                ("lname", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200, unique=True)),
                ("pwd", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Student_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=200, unique=True)),
                (
                    "username",
                    models.CharField(default="None", max_length=200, unique=True),
                ),
                ("cnic", models.CharField(default="None", max_length=200, unique=True)),
                ("phone", models.CharField(default="None", max_length=200)),
                ("skills", models.TextField(default=[])),
                (
                    "description",
                    models.CharField(default="No description", max_length=2000),
                ),
                ("profile", models.CharField(default="None", max_length=200)),
                ("institute", models.CharField(default="None", max_length=200)),
                ("inst_email", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supervisor_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=200, unique=True)),
                (
                    "username",
                    models.CharField(default="None", max_length=200, unique=True),
                ),
                ("cnic", models.CharField(default="None", max_length=200, unique=True)),
                ("phone", models.CharField(default="None", max_length=200)),
                ("skills", models.TextField(default=[])),
                (
                    "description",
                    models.CharField(default="No description", max_length=2000),
                ),
                ("profile", models.CharField(default="None", max_length=200)),
                ("institute", models.CharField(default="None", max_length=200)),
                ("inst_email", models.CharField(max_length=200, unique=True)),
                ("designation", models.CharField(default="None", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proposal_time", models.DateTimeField(auto_now_add=True)),
                ("user_name", models.CharField(max_length=200)),
                ("proposal_message", models.TextField()),
                (
                    "job_id",
                    models.ForeignKey(
                        default="None",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend_app.jobs",
                        to_field="job_id",
                    ),
                ),
            ],
        ),
    ]
