# Generated by Django 5.1.3 on 2024-12-07 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0003_alter_jobs_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place_orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=200)),
                ("order_time", models.DateTimeField(auto_now_add=True)),
                ("budget", models.FloatField()),
                ("end_date", models.TextField()),
                (
                    "job_id_id",
                    models.ForeignKey(
                        default="None",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend_app.jobs",
                        to_field="job_id",
                    ),
                ),
            ],
        ),
    ]
