# Generated by Django 5.1.3 on 2024-12-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0008_rename_job_id_id_id_place_orders_job_id_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place_orders",
            name="budget",
            field=models.IntegerField(),
        ),
    ]
