# Generated by Django 5.1.3 on 2024-12-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0009_alter_place_orders_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place_orders",
            name="end_date",
            field=models.DateTimeField(),
        ),
    ]
