# Generated by Django 5.1.3 on 2024-12-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0012_alter_place_orders_job_id_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place_orders",
            name="job_id_id",
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="job_id_id",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.AlterField(
            model_name="company_data",
            name="profile",
            field=models.ImageField(blank=True, null=True, upload_to="company_images/"),
        ),
        migrations.AlterField(
            model_name="student_data",
            name="profile",
            field=models.ImageField(blank=True, null=True, upload_to="student_images/"),
        ),
        migrations.AlterField(
            model_name="supervisor_data",
            name="profile",
            field=models.ImageField(
                blank=True, null=True, upload_to="supervisor_images/"
            ),
        ),
        migrations.DeleteModel(
            name="Place_orders",
        ),
        migrations.DeleteModel(
            name="Jobs",
        ),
        migrations.DeleteModel(
            name="Proposal",
        ),
    ]
