# Generated by Django 5.1.3 on 2025-01-06 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0013_client_db_student_db_supervisor_db_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place_orders",
            name="job_id_id",
            field=models.ForeignKey(
                default="None",
                on_delete=django.db.models.deletion.CASCADE,
                to="backend_app.jobs",
                to_field="job_id",
            ),
        ),
    ]
