# Generated by Django 5.1.3 on 2024-12-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0013_remove_place_orders_job_id_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client_db",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200, unique=True)),
                ("cnic", models.CharField(default="None", max_length=200, unique=True)),
                ("phone", models.CharField(default="None", max_length=200)),
                ("description", models.TextField()),
                (
                    "profile",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_images/"
                    ),
                ),
                ("joiningType", models.CharField(default="None", max_length=200)),
                (
                    "email",
                    models.CharField(default="None", max_length=200, unique=True),
                ),
                ("organizationName", models.CharField(default="None", max_length=200)),
                (
                    "organizationEmail",
                    models.CharField(default="None", max_length=200, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student_db",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200, unique=True)),
                ("cnic", models.CharField(default="None", max_length=200, unique=True)),
                ("phone", models.CharField(default="None", max_length=200)),
                ("description", models.TextField()),
                (
                    "profile",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_images/"
                    ),
                ),
                ("degree", models.CharField(default="None", max_length=200)),
                ("major", models.CharField(default="None", max_length=200)),
                ("semester", models.CharField(default="None", max_length=200)),
                ("institute", models.CharField(default="None", max_length=200)),
                (
                    "email",
                    models.CharField(default="None", max_length=200, unique=True),
                ),
                (
                    "university_email",
                    models.CharField(default="None", max_length=200, unique=True),
                ),
                ("skills", models.TextField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name="Supervisor_db",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200, unique=True)),
                ("cnic", models.CharField(default="None", max_length=200, unique=True)),
                ("phone", models.CharField(default="None", max_length=200)),
                ("description", models.TextField()),
                (
                    "profile",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_images/"
                    ),
                ),
                ("designation", models.CharField(default="None", max_length=200)),
                ("department", models.CharField(default="None", max_length=200)),
                (
                    "email",
                    models.CharField(default="None", max_length=200, unique=True),
                ),
                ("institute", models.CharField(default="None", max_length=200)),
                (
                    "university_email",
                    models.CharField(default="None", max_length=200, unique=True),
                ),
                ("skills", models.TextField(default=[])),
            ],
        ),
        migrations.DeleteModel(
            name="Company_data",
        ),
        migrations.DeleteModel(
            name="Student_data",
        ),
        migrations.DeleteModel(
            name="Supervisor_data",
        ),
    ]
