# Generated by Django 5.1.3 on 2024-12-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0014_client_db_student_db_supervisor_db_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client_db",
            name="profile",
            field=models.ImageField(blank=True, null=True, upload_to="client_images/"),
        ),
        migrations.AlterField(
            model_name="supervisor_db",
            name="profile",
            field=models.ImageField(
                blank=True, null=True, upload_to="supervisor_images/"
            ),
        ),
    ]
